name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: cd ${{ github.workspace }}
      - run: ./main.exe